name: CI
on: push
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm ci
      - run: npm run build
      - run: npm run pkg
      - run: |
          # Rename these files for a nicer release
          mkdir -p ./dist/pkg/linux; mv ./dist/pkg/cli-linux ./dist/pkg/linux/hundredpoints;
          mkdir -p ./dist/pkg/macos; mv ./dist/pkg/cli-macos ./dist/pkg/macos/hundredpoints;
          mkdir -p ./dist/pkg/windows; mv ./dist/pkg/cli-win.exe ./dist/pkg/windows/hundredpoints.exe;
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HUSKY: 0
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
